### ISSUE TITLE
Issue linking to cupti with 2.6.0

### ISSUE THREAD

**Issue by corbett5** [LLNL/Caliper#385]
When building 2.6.0 with CUDA 101.243 on Lassen I get the following error when linking the the user application

```
/usr/bin/ld: warning: libcupti.so.10.1, needed by /usr/WS2/corbett5/TC02350/uberenv-libs/linux-rhel7-ppc64le/clang-11.0.1/caliper-2.6.0-olcrcfanb2ezov4spvbsu732we7f7qc5/lib64/libcaliper.so.2.6.0, not found (try using -rpath or -rpath-link)
/usr/WS2/corbett5/TC02350/uberenv-libs/linux-rhel7-ppc64le/clang-11.0.1/caliper-2.6.0-olcrcfanb2ezov4spvbsu732we7f7qc5/lib64/libcaliper.so.2.6.0: undefined reference to `cuptiSetEventCollectionMode@libcupti.so.10.1'
...
Many more undefined references
```

This is my CMake setup

```CMake
find_package(caliper REQUIRED PATHS ${CALIPER_DIR})
```

With the following modification it works

```CMake
find_package(caliper REQUIRED PATHS ${CALIPER_DIR})
blt_register_library(NAME caliper
                     INCLUDES ${caliper_INCLUDE_PATH}
                     LIBRARIES caliper /usr/tce/packages/cuda/cuda-10.1.243/extras/CUPTI/lib64/libcupti.so
                     TREAT_INCLUDES_AS_SYSTEM ON)
```

I think Caliper isn't exporting its dependency on cupti. It works with CUDA 11.4.1 but my guess is that's because `libcupti` is in the CUDA library directory which is already added to the dynamic library search path.

**Comment by daboehme** [comment]
Hi @corbett5 ,

Thanks for reporting. Normally Caliper adds the correct rpaths to its dependencies, including cupti. I'm not seeing this issue with a manual build. It might have something to do with spack, I think it rewrites the rpaths but it does not know about the different link directory for CUPTI.

Is your workaround a viable solution for now? If it is, I might leave it alone for now given that it only affects older cuda versions. Otherwise, if spack is the issue, then the best fix might be to update the spack package to include the cupti rpath, or I can try exporting the cupti dependency in cmake.

**Comment by corbett5** [comment]
With spack it passes `CUPTI_DIR=/usr/tce/packages/cuda/cuda-10.1.243/`, but this seems OK because Caliper has some internal logic to find the real directory and can verify from the output that it does indeed find `/usr/tce/packages/cuda/cuda-10.1.243/extras/CUPTI/lib64/libcupti.so`.

With a manual build does the dependency get propagated to the CMake package as well?

**Comment by daboehme** [comment]
With a manual build the rpaths to cupti should be set correctly.
